var references = {'icons': {}}
points.forEach((data, pointindex) => {
    let categoryname = `category_${(data.category != '' && data.category != undefined) ? data.category.toLowerCase().replaceAll(' ','_') : 'miscellaneous'}`
    let sectionname = `section_${(data.section != '' && data.section != undefined) ? data.section.toLowerCase().replaceAll(' ','_') : 'miscellaneous'}`

    
    if (!references[sectionname]) {
        // Create section header
        let categoryheader = document.createElement('div')
        categoryheader.innerHTML = (data.section != '' && data.section != undefined) ? data.section : 'Miscellaneous'
        categoryheader.classList.add('points_categoryheader')
        points_container.appendChild(categoryheader)

        // Create section container
        let sectioncontainer = document.createElement('div')
        sectioncontainer.id = sectionname
        sectioncontainer.classList.add('points_categorysection')
        points_container.appendChild(sectioncontainer)

        // Add Section
        references[sectionname] = {
            'element': sectioncontainer
        }
    }


    if (!references[sectionname][categoryname]) {
        // Create generic category container element
        let categorycontainer = document.createElement('button')
        categorycontainer.id = categoryname
        categorycontainer.classList.add('points_sectionbutton')
        references[sectionname].element.appendChild(categorycontainer)

        // Icon
        let categoryicon = document.createElement('img')
        categoryicon.src = './autogenerated/1085967092072845463.webp'
        // categoryicon.src = '../icons/glowing_cyan_argemia.png'
        categoryicon.classList.add('points_secbuttonimg')
        categorycontainer.appendChild(categoryicon)

        // Text label
        let categorylabel = document.createElement('span')
        categorylabel.innerHTML = (data.category != '' && data.category != undefined) ? data.category : 'Miscellaneous'
        categorylabel.classList.add('points_secbuttontext')
        categorycontainer.appendChild(categorylabel)

        // Add references
        references[sectionname][categoryname] = {
            'element': categorycontainer
        }
    }
})


{/* <div class="points_categoryheader">Plushes</div>
<div class="container"></div> */}